### ISSUE TITLE
Repository showing "excluded" on Hacktoberfest offical website

### ISSUE THREAD

**Issue by Atv23** [MU-Enigma/Hacktoberfest24#10]
After I made a commit on a WebDev Level-1 project, the status for this repository is showing as "excluded" on the official Hacktoberfest 24 website. Wasted all my time contributing in this repo

**Comment by Enigma-Admin** [comment]
Thank you for bringing this to our attention, and I’m really sorry to hear about the frustration you’re experiencing. We understand how disheartening it can be to put in the effort and not see your contribution counted, and we truly appreciate your hard work on the WebDev Level-1 project.

We’re currently investigating why the repository was marked as excluded on the official Hacktoberfest 24 website, and we’ve already reached out to the Hacktoberfest organizers to resolve the issue. We're doing everything we can to get this sorted out as quickly as possible.

In the meantime, please don’t feel that your contribution was wasted—it’s valuable to us and the community. We’ll keep you updated on the situation, and we hope to have a solution soon.

Thanks for your understanding and patience.
